<?xml version="1.0" encoding="utf-8"?>
<Database Name="KMERPH" Class="HeadquartersDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PLA-PP\SQLEXPRESS;Initial Catalog=KMERPH;Integrated Security=True" SettingsObjectName="KMERP.Headquarters.Properties.Settings" SettingsPropertyName="KMERPHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.buyerinfos" Member="buyerinfos">
    <Type Name="buyerinfos">
      <Column Name="id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usercode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="odes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cdatetime" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ptypes" Member="ptypes">
    <Type Name="ptypes">
      <Column Name="id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="usercode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pcode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="psize" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="seasontype" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="manorwoman" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="cdes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cdatetime" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stocks" Member="stocks">
    <Type Name="stocks">
      <Column Name="id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usercode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fullname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sdes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.clothinginstocks" Member="clothinginstocks">
    <Type Name="clothinginstocks">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="incount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inprice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="minsaleprice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="willprice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="instockdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hasoutstock" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.batsales" Member="batsales">
    <Type Name="batsales">
      <Column Name="id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="bid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="saleprice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="salecount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="totalmoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="saledate" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
    </Type>
  </Table>
</Database>