<?xml version="1.0" encoding="utf-8"?>
<Database Name="KMERPR" Class="UserDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PLA-PP\SQLEXPRESS;Initial Catalog=KMERPR;Integrated Security=True" SettingsObjectName="KMERP.Retalier.Properties.Settings" SettingsPropertyName="KMERPRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.operators" Member="operators">
    <Type Name="operators">
      <Column Name="id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usercode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isadmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>